PUT http://localhost:3000/api/reserva/actualizar HTTP/1.1
Content-Type: application/json

{
    "id": "66",
    "estado": "SUSESFUL",
    "f_entrada": "2024-05-20",
    "f_salida": "2024-05-23",
    //"id_Cliente": "0",
    //"id_Empleado": "0",
    //"id_Habitacion": "3",
    "precio": 1000,
    "descripcion": null,
    "habilitado": false
}
