// Archivo crearReserva.http
PUT http://localhost:3000/api/habitacion/actualizar HTTP/1.1
Content-Type: application/json

{
    "id": "14",
   // "tipo": "SENCILLA",
    //"precio": 999,
   // "estado": "Ocupada",
    //"capacidad": 22,
    "habilitado": false
}
