// Archivo crearReserva.http
POST http://localhost:3000/api/reserva/insertar HTTP/1.1
Content-Type: application/json

{
    "estado": "BRUTAL",
    "f_entrada": "2024-06-01",
    "f_salida": "2024-06-10",
    "id_Cliente": "789",
    "id_Empleado": "123",
    "id_Habitacion": "020"
}
