POST http://localhost:3000/api/empleado/insertar HTTP/1.1
Content-Type: application/json

{
    "id": "999",
    "contrasenia": "deshabilitado",
    "correo": "nixter646464@gmail.com",
    "nombre": "Deshabilitado Perez",
    "fecha_nacimiento": "2004-02-10",
    "direccion": "Calle Esternocleidomastoideo",
    "salario": 1000,
    "telefono": "12345678",
    "fecha_inicio": "2024-05-04"
}
